# Generated by Django 5.2 on 2025-05-01 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Main Bot", max_length=100, verbose_name="Имя бота"
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(default=False, verbose_name="Забанен"),
                ),
                (
                    "banned_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Забанен до"
                    ),
                ),
            ],
            options={
                "verbose_name": "Бот",
                "verbose_name_plural": "Боты",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст сообщения")),
                (
                    "is_second_touch",
                    models.BooleanField(default=False, verbose_name="Второе касание"),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="PendingUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Telegram ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Имя"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="Обработан"),
                ),
            ],
            options={
                "verbose_name": "Пользователь в очереди",
                "verbose_name_plural": "Пользователи в очереди",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_interval_minutes",
                    models.IntegerField(
                        default=6, verbose_name="Интервал между сообщениями (минуты)"
                    ),
                ),
                (
                    "ban_freeze_minutes",
                    models.IntegerField(
                        default=60, verbose_name="Заморозка после бана (минуты)"
                    ),
                ),
                (
                    "second_touch_delay_minutes",
                    models.IntegerField(
                        default=1440, verbose_name="Задержка второго касания (минуты)"
                    ),
                ),
                (
                    "admin_telegram_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Telegram ID админа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка",
                "verbose_name_plural": "Настройки",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Telegram ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Имя"),
                ),
                (
                    "responded",
                    models.BooleanField(default=False, verbose_name="Ответил"),
                ),
                (
                    "last_message_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время последнего сообщения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="SecondTouchSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(verbose_name="Время добавления"),
                ),
                (
                    "original_scheduled_time",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Изначальное время добавления",
                    ),
                ),
                ("sent", models.BooleanField(default=False, verbose_name="Отправлено")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bots.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bots.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Второе касание",
                "verbose_name_plural": "Вторые касания",
            },
        ),
        migrations.CreateModel(
            name="FirstTouchSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(verbose_name="Время добавления"),
                ),
                (
                    "original_scheduled_time",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Изначальное время добавления",
                    ),
                ),
                ("sent", models.BooleanField(default=False, verbose_name="Отправлено")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bots.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bots.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Первое касание",
                "verbose_name_plural": "Первые касания",
            },
        ),
    ]
