# Generated by Django 5.2 on 2025-04-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0002_account_remove_schedule_bot_schedule_account_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="api_hash",
        ),
        migrations.RemoveField(
            model_name="account",
            name="api_id",
        ),
        migrations.RemoveField(
            model_name="account",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="account",
            name="session_string",
        ),
    ]
