# Generated by Django 5.2 on 2025-04-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0003_remove_account_api_hash_remove_account_api_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="account",
        ),
        migrations.DeleteModel(
            name="Account",
        ),
    ]
