# Generated by Django 5.2 on 2025-04-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0004_remove_schedule_account_delete_account"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={"verbose_name": "Расписание", "verbose_name_plural": "Расписания"},
        ),
        migrations.AlterModelOptions(
            name="settings",
            options={"verbose_name": "Настройка", "verbose_name_plural": "Настройки"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="message",
            name="is_second_touch",
            field=models.BooleanField(default=False, verbose_name="Второе касание"),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(verbose_name="Текст сообщения"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bots.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="scheduled_time",
            field=models.DateTimeField(verbose_name="Время отправки"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="sent",
            field=models.BooleanField(default=False, verbose_name="Отправлено"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bots.user",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="ban_freeze_hours",
            field=models.IntegerField(
                default=3, verbose_name="Заморозка после бана (часы)"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="message_interval_minutes",
            field=models.IntegerField(
                default=6, verbose_name="Интервал между сообщениями (минуты)"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="second_touch_delay_hours",
            field=models.IntegerField(
                default=24, verbose_name="Задержка второго касания (часы)"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_message_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время последнего сообщения"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="responded",
            field=models.BooleanField(default=False, verbose_name="Ответил"),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Telegram ID"
            ),
        ),
    ]
