# Generated by Django 5.2 on 2025-04-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0005_alter_message_options_alter_schedule_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="second_touch_delay_hours",
        ),
        migrations.AddField(
            model_name="settings",
            name="second_touch_delay_minutes",
            field=models.IntegerField(
                default=1440, verbose_name="Задержка второго касания (минуты)"
            ),
        ),
    ]
