# Generated by Django 5.2 on 2025-04-29 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0006_remove_settings_second_touch_delay_hours_and_more"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Main Bot", max_length=100, verbose_name="Имя бота"
                    ),
                ),
                (
                    "is_banned",
                    models.BooleanField(default=False, verbose_name="Забанен"),
                ),
                (
                    "banned_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Забанен до"
                    ),
                ),
            ],
            options={
                "verbose_name": "Бот",
                "verbose_name_plural": "Боты",
            },
        ),
        migrations.AddField(
            model_name="schedule",
            name="clocked_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.clockedschedule",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="periodic_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.periodictask",
            ),
        ),
    ]
