# Generated by Django 5.2 on 2025-04-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0007_bot_schedule_clocked_schedule_schedule_periodic_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="ban_freeze_hours",
        ),
        migrations.AddField(
            model_name="settings",
            name="ban_freeze_minutes",
            field=models.IntegerField(
                default=60, verbose_name="Заморозка после бана (минуты)"
            ),
        ),
    ]
