# Generated by Django 5.2 on 2025-05-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0008_remove_settings_ban_freeze_hours_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="clocked_schedule",
        ),
    ]
