# Generated by Django 5.2 on 2025-05-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0002_initial_data"),
        ("bots", "0009_remove_schedule_clocked_schedule"),
    ]

    operations = []
